version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=michael1800%
      - MYSQL_DATABASE=trazabilidad

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: michael1800%
      MYSQL_DATABASE: trazabilidad
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: